### ISSUE TITLE
cd verb is unknown to colcon?!

### ISSUE THREAD

**Issue by rhaschke** [colcon/colcon-cd#21]
The `cd` verb is unknown to colcon:

```
$ colcon cd my_package
              ...
colcon: error: argument verb_name: invalid choice: 'cd' (choose from 'alias', 'build', 'clean', 'extension-points', 'extensions', 'graph', 'info', 'list', 'metadata', 'mixin', 'test', 'test-result', 'version-check', 'clr')
```

**Comment by Briancbn** [comment]
Hi @rhaschke, `colcon_cd` is a shell function, instead of a script.

You can follow the guide to setup based on your current environment
https://colcon.readthedocs.io/en/released/user/installation.html#quick-directory-changes

If you installed using Debian binary, it will be like the following
```bash
source /usr/share/colcon_cd/function/colcon_cd.sh
```

The usage is like this
```bash
colcon_cd <package-name>
```

**Comment by rhaschke** [comment]
I have sourced colcon_cd.sh, but nevertheless, I do get the error mentioned above. I can directly call the shell function: 
`colcon_cd my_package`
but using `cd` as a verb doesn't work.

**Comment by Briancbn** [comment]
`cd` verb is not the intended usage. https://github.com/colcon/colcon-cd/pull/1#issuecomment-538463246 explains why it might not be feasible at this point.

**Comment by rhaschke** [comment]
I see. I think this subtlety should be better documented [here](https://colcon.readthedocs.io/en/released/user/installation.html#quick-directory-changes).
